TeacherWorkSpace/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('workspace/', include('workspace.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', include('workspace.urls')), #temp
]

workspace/urls.py
from django.urls import path

from . import views

app_name = 'workspace'
urlpatterns = [
    path(r'', views.index_view, name='index'),
    path(r'login/', views.MyLoginView.as_view(), name='login'),
    path(r'logout/', views.logout_view, name='logout'),
    path(r'profile/', views.profile_view, name='profile'),
    path(r'profile/edit', views.edit_profile_view, name='profile_edit'),

    path(r'schedule/', views.schedule_view, name='schedule'),
    path(r'lesson/<int:l_id>/', views.lesson_view, name='lesson_detail'),
    path(r'lesson/<int:l_id>/edit', views.lesson_edit_view, name='lesson_edit'),
    path(r'lesson/add', views.lesson_add_view, name='lesson_add'),

    path(r'marks/', views.marks_menu_view, name="marks_menu"),
    path(r'marks/course/<int:c_id>/', views.marks_entities_view, name="marks_entities"),
    path(r'marks/course/<int:c_id>/table', views.marks_table_view, name="marks_table"),
    path(r'marks/course/<int:c_id>/add', views.marks_add_entities_view, name="marks_add_ent"),
    path(r'marks/course/<int:c_id>/ce/<int:e_id>/', views.marks_detail_view, name="marks_detail"),
    path(r'marks/course/<int:c_id>/ce/<int:e_id>/change/', views.marks_change_ent_view, name="marks_entity_change"),
    path(r'marks/course/<int:c_id>/ce/<int:e_id>/edit/', views.marks_edit_view, name="marks_edit"),
    path(r'marks/course/<int:c_id>/ce/<int:e_id>/rm/', views.marks_rm_ce_view, name="marks_entity_rm"),

    path(r'batch_add/', views.batch_add_lessons_view, name='batch_add'),
    path(r'course/wh/github/<int:c_id>-<int:s_id>/', views.webhook_github_view, name='github_wh'),
    path(r'notification/remove/<int:n_id>', views.rm_notification, name='rm_notif'),
    path(r'loc/<lat>,<lon>', views.ShowLocationView.as_view(), name='get_loc'),
]

workspace/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.validators import UnicodeUsernameValidator
import datetime
import workspace.models as wsm

DAY_CHOICES = [(0, "MON"), (1, "TUE"), (2, "WEN"), (3, "THU"), (4, "FRI"), (5, "SAT"), (6, "SUN")]


class AttCheckForm(forms.Form):
    """
        Form for marking attendance by student
    """
    lon = forms.FloatField(widget=forms.HiddenInput)
    lat = forms.FloatField(widget=forms.HiddenInput)


class AttStartForm(forms.Form):
    """
        Form for creating attendance token by teacher
    """
    minutes = forms.IntegerField(label='Minutes for attendance', initial=10)


class MarkForm(forms.Form):
    """
        Form for creating/changing mark for student, used to create MarkFormSet
        in views.marks_edit_view, ControlEntity defined in view
    """
    student = forms.ModelChoiceField(label='Student', queryset=wsm.Student.objects.none(),
                                     empty_label=None, widget=forms.HiddenInput)
    mark = forms.DecimalField(label='Mark', max_digits=4, decimal_places=1, required=False)

    def __init__(self, *args, **kwargs):
        """
        __init__() if 'student_group' parameter passed overrides student
         field with another queryset, presumably - set of students in course group
        """
        try:
            qs = kwargs.pop('student_group')
        except KeyError:
            qs = None
        finally:
            super().__init__(*args, **kwargs)
            if qs:
                self.fields["student"] = forms.ModelChoiceField(label='Student', queryset=qs, empty_label=None,
                                                                widget=forms.HiddenInput)


class LessonForm(forms.Form):
    l_type = forms.ModelChoiceField(label='Type', queryset=wsm.LessonType.objects.all(), required=False)
    location = forms.ModelChoiceField(label='Location', queryset=wsm.Location.objects.all(), required=False)
    date = forms.DateField(label='Date', widget=forms.SelectDateWidget)
    time = forms.TimeField(label='Lesson start time', widget=forms.TimeInput)


class LessonAddForm(LessonForm):
    discipline = forms.ModelChoiceField(label='Discipline', queryset=wsm.Discipline.objects.all(), empty_label=None)
    group = forms.ModelChoiceField(label='Student group', queryset=wsm.StudentGroup.objects.all(), empty_label=None)


class BatchLessonsForm(LessonAddForm):
    """
        Form for creating multiple identical lessons for given period with given day and time
        Used in views.batch_add_lessons_view by staff
    """
    date = None
    teacher = forms.ModelChoiceField(label='Teacher', queryset=wsm.Teacher.objects.all(), empty_label=None)

    day = forms.ChoiceField(label='Day of the week', choices=DAY_CHOICES)
    week = forms.BooleanField(label='Each of 2 weeks?',)
    start_date = forms.DateField(label='Start date (week)', widget=forms.SelectDateWidget())
    end_date = forms.DateField(label='Last date (week)', widget=forms.SelectDateWidget)

    field_order = ['discipline', 'teacher', 'group', 'l_type', 'location',
                   'time', 'day', 'week', 'start_date', 'end_date']


class ControlEntityForm(forms.ModelForm):
    """
            Form for teacher to add new control entity to his course
    """
    class Meta:
        model = wsm.ControlEntity
        fields = ['name', 'etype', 'deadline', 'mark_max', 'materials']
        error_messages = {
            NON_FIELD_ERRORS: {'unique_together': "%(model_name)s's %(field_labels)s are not unique.", }
        }
        labels = {
            'etype': "Control type"
        }
        widgets = {
            # 'course': forms.HiddenInput(),
            'deadline': forms.SelectDateWidget()
        }


class ControlEntityChangeForm(ControlEntityForm):
    class Meta(ControlEntityForm.Meta):
        exclude = ['etype', ]


class ProfileBaseForm(forms.Form):
    username = forms.CharField(label='Username/Login', max_length=30,
                               required=False, validators=[UnicodeUsernameValidator])
    email = forms.EmailField(label="E-mail", required=False)


class ProfileStudentForm(ProfileBaseForm):
    github = forms.URLField(label="Github page", required=False)


class ProfileTeacherForm(ProfileBaseForm):
    page = forms.URLField(label="Personal page", required=False)


"""class ControlEntityForm(forms.Form):

    etype = forms.ModelChoiceField(label='Category', queryset=wsm.ControlCategory.objects.all(), empty_label=None)
    name = forms.CharField(label='Title')
    deadline = forms.DateField(label='Deadline', widget=forms.SelectDateWidget)
    mark_max = forms.DecimalField(label='Maximal mark', max_digits=4, decimal_places=1)
    materials = forms.CharField(label='Study materials', required=False)"""

workspace/views.py
import json
import datetime
import pytz
import tzlocal

from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponseBadRequest
from django.contrib.auth import login, logout, views as auth_views, models as auth_models
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import RedirectView
from django.db.utils import IntegrityError
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.shortcuts import get_object_or_404, render, redirect
from django.forms import formset_factory
from TeacherWorkSpace.settings import DEBUG

import workspace.models as wsm
import workspace.forms as wsf

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
TZ_TARGET = tzlocal.get_localzone()  # datetime.datetime.now().astimezone().tzinfo     #EEST
TIME_FORMAT = "%T %z"
DATE_FORMAT = "%d.%m.%Y"
DT_FORMAT = DATE_FORMAT + " " + TIME_FORMAT
SCHEDULE_TIME = [datetime.time(8, 30, 0, 0, tzinfo=TZ_TARGET),
                 datetime.time(10, 25, 0, 0, tzinfo=TZ_TARGET),
                 datetime.time(12, 20, 0, 0, tzinfo=TZ_TARGET),
                 datetime.time(14, 15, 0, 0, tzinfo=TZ_TARGET),
                 datetime.time(16, 10, 0, 0, tzinfo=TZ_TARGET)]
COMMIT_TAG = "[WS]"
LOCATION_URL = "https://www.google.com/maps/place/%(lat)s,%(lon)s/@%(lat)s,%(lon)s,15z"
LAT_DELTA = 0.000210
LON_DELTA = 0.000370

CUSTOM_CONTEXT_FUNC = (lambda request, view, **kwargs: {})


def get_custom_context(request, view, **kwargs):  # example of integrated function
    """
     Function for creating dictionary of custom context variables
     for passing to basic view to be rendered in template
     :param request: request from view
     :param view: actual view that needs context
     :param kwargs: additional arguments
     :return: list of tuples (:model:`workspace.Student`, [float, None])
     """
    custom_context = dict()
    if view == marks_entities_view:
        if 'course' in kwargs:
            a_course = kwargs['course']
            if a_course.discipline.name == "Math" or a_course.discipline.name == "Algoritms":
                custom_context["auth_student"] = request.user.student
        return custom_context


CUSTOM_CONTEXT_FUNC = get_custom_context


def index_view(request):
    """
    Index view for app with placeholder content

    **Context**

    ``notifications``
    Notifications for current :model:`auth.User`.

    **Template:**

    :template:`workspace/index.html`
    """
    context = {}
    # nn = wsm.Notification.objects.all()
    # for n in nn:
    #     if n.expire < TZ_TARGET.localize(datetime.datetime.now()) or n.user.count() == 0:
    #         n.delete()
    try:
        lesson_list = wsm.Lesson.objects.order_by('-datetime')[:10]
        context['lesson_list'] = lesson_list
    except wsm.Lesson.DoesNotExist:
        print("no lessons")
    if request.user.is_authenticated:
        context["notifications"] = request.user.notification_set.all().order_by("created")[:10]
    return render(request, "workspace/index.html", context)


def get_attendance(les):
    """
        Function for creating list for attendance (alphabetic ordering) of tuples (student, presence)
        :param les: current lesson
        :return: list of tuples (:model:`workspace.Student`, string)
    """
    att_set = les.attendance_set.all()
    #if att_set.count() > 0:
    st_set = les.group.student_set.all().order_by("user__last_name")
    result_list = []
    for st in st_set:
        att = att_set.filter(student=st)
        if att.count() == 1:
            att = att[0]
            if abs(att.lat - les.location.lat) < LAT_DELTA and abs(att.lon - les.location.lon) < LON_DELTA:
                result_list.append((st, 'Present'))
            else:
                result_list.append((st, 'Recorded'))
        else:
            result_list.append((st, 'Absent'))
    return result_list

def lesson_view(request, l_id):
    """
    View of particular lesson, also used to mark attendance by related teacher/students

    **Context**

    ``notifications``
    Notifications for current :model:`auth.User`.
    ``c_message``
    Notification message to render
    ``chosen_lesson``
    Current :model:`workspace.Lesson`
    ``auth_teacher``
    Current :model:`auth.User` if it is teacher
    ``auth_student``
    Current :model:`auth.User` if it is related student
    ``editable``
    Flag that shows if lesson can be modified
    ``at_form``
    Rendered form, forms.AttStartForm for viable teacher,
    forms.AttCheckForm for viable student if attendance started

    **Template:**

    :template:`workspace/lesson_detail.html`
    """
    chosen_lesson = get_object_or_404(wsm.Lesson, pk=l_id)
    context = {'chosen_lesson': chosen_lesson}
    if request.user.is_authenticated:
        if request.user.groups.filter(name="Teachers"):                                     # Teacher perspective
            if request.user == chosen_lesson.teacher.user:       # Correct teacher
                context['auth_teacher'] = request.user
                if (not DEBUG and datetime.date.today() >= chosen_lesson.datetime.date()) or DEBUG:
                    context['att_tab'] = get_attendance(chosen_lesson)      # Show attendance
                if (not DEBUG and datetime.date.today() <= chosen_lesson.datetime.date()) or DEBUG:     # has not passed
                    context['editable'] = True
                    if (not DEBUG and datetime.date.today() == chosen_lesson.datetime.date()) or DEBUG:     # right day
                        tok = wsm.AttendanceToken.objects.filter(lesson=chosen_lesson)
                        if not tok:
                            # No token for this lesson (no repeat)
                            if request.method == 'POST':        # Form sent
                                at_form = wsf.AttStartForm(request.POST)
                                if at_form.is_valid():
                                    at_token = wsm.AttendanceToken()
                                    at_token.lesson = chosen_lesson
                                    t = TZ_TARGET.localize(datetime.datetime.now())  # local current time
                                    at_token.expire = t + datetime.timedelta(minutes=at_form.cleaned_data['minutes'])
                                    at_token.save()                                  # New attendance token created
                                    context['c_message'] = str("Timer started")
                                    nn = wsm.Notification()
                                    nn.note = "Lesson {} started ".format(chosen_lesson)
                                    nn.link = reverse("workspace:lesson_detail", args=[chosen_lesson.id])
                                    nn.expire = t + datetime.timedelta(hours=2, minutes=30)
                                    nn.created = t
                                    nn.save()
                                    nn.user.set(auth_models.User.objects.filter(student__group=chosen_lesson.group))
                                    # for student in chosen_lesson.group.student_set.all():
                                    # nn.user.add(student.user)
                                    nn.save()
                                else:
                                    context['at_form'] = at_form
                                    context['c_message'] = str("Error in form")
                            else:                   # Initial form view
                                context['at_form'] = wsf.AttStartForm()
                        else:
                            tok = tok[0]
                            if tok.expire < TZ_TARGET.localize(datetime.datetime.now()):
                                tok.delete()
                                context['c_message'] = "Old token expired"
        elif request.user.groups.filter(name="Students"):                                   # Student perspective
            if request.user.student.group == chosen_lesson.group:           # Correct student
                context['auth_student'] = request.user    # maybe check for repeats
                at_tok = wsm.AttendanceToken.objects.filter(lesson=chosen_lesson)
                if at_tok.exists():                         # If attendance available
                    at_tok = at_tok[0]
                    if TZ_TARGET.localize(datetime.datetime.now()) < at_tok.expire:  # In time
                        if request.method == 'POST':        # Form sent
                            at_form = wsf.AttCheckForm(request.POST)
                            if at_form.is_valid():      # Valid values
                                t_lat = at_form.cleaned_data['lat']
                                t_lon = at_form.cleaned_data['lon']
                                if -180 < t_lat < 180 and -90 < t_lon < 90:  # Valid values (add validator?)
                                    try:
                                        attendance, cr = wsm.Attendance.objects\
                                            .get_or_create(student=request.user.student, lesson=chosen_lesson,
                                                           defaults={'lon': t_lon, 'lat': t_lat})
                                        attendance.lat = t_lat
                                        attendance.lon = t_lon
                                        attendance.save()
                                        if chosen_lesson.location:
                                            if abs(t_lat - chosen_lesson.location.lat) < LAT_DELTA\
                                                    and abs(t_lon - chosen_lesson.location.lon) < LON_DELTA:
                                                # square accept zone
                                                # delta 0.000210 lat 0.000370 lon for ~ 50*50 m from center

workspace/templates/workspace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Base Page{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="shortcut icon" href="{% static 'workspace/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'workspace/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'workspace/general.css' %}">
    <script type="text/javascript" src="{% static 'workspace/popup.js' %}"></script>
    {% block scr %} {% endblock %}
</head>
<body>

<h2 class="header">{% block title2 %}Base Page{% endblock %}</h2>
<div class="Mcontainer">
    <div class = "row">
        <div class="col-lg-2" id="sidebar" >
            {% include "./sidebar.html" %}
        </div>
        <div class="col-lg-10 content">
            {% block content %} err {% endblock %}
        </div>
        </h2>
    </div>
    <footer></footer>
</div>
</body>
</html>

workspace/templates/workspace/batch_add.html
{% extends "./generic_edit.html" %}

{% block title %} Batch {% endblock %}
{% block title2 %} Batch add lessons {% endblock %}

{% block action_url %} {% url 'workspace:batch_add' %} {% endblock %}

workspace/templates/workspace/index.html
{% extends "./base.html" %}

{% block title %} Workspace {% endblock %}
{% block title2 %} Index page {% endblock %}

{% block content %}
    <div style="padding-bottom:1000px">
        <h4> Welcome to automated teacher's workspace</h4>
        <p class="mytmp"> Created by Troian Borys, KV-62 in 2020 </p>
        {% if lesson_list %}
            <p class="mytmp"> Latest lessons (Placeholder): </p>
            <ul>
            {% for lesson in lesson_list %}
                <li><a href="{% url 'workspace:lesson_detail' lesson.id %}">
                    {{ lesson.discipline.name }} {{ lesson.group.name }}
                </a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No lessons</p>
        {% endif %}
    </div>
{% endblock %}

workspace/templates/workspace/lesson_add.html
{% extends "./generic_edit.html" %}

{% block title %} Add lesson {% endblock %}
{% block title2 %} Add lesson {% endblock %}
{% block action_url %} {% url 'workspace:lesson_add' %} {% endblock %}
{% block subheader %} <h5> Add lesson : </h5> {% endblock %}

workspace/templates/workspace/lesson_edit.html
{% extends "./generic_edit.html" %}

{% block title %} Edit lesson {% endblock %}
{% block title2 %} Edit lesson {% endblock %}
{% block action_url %} {% url 'workspace:lesson_edit' chosen_lesson.id %} {% endblock %}
{% block subheader %} <h5> Edit lesson {{ chosen_lesson }}: </h5> {% endblock %}

workspace/templates/workspace/login.html
{% extends "./base.html" %}

{% block title %} Login page {% endblock %}
{% block title2 %} Login {% endblock %}

{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'workspace:login' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>
    <input type="submit" class="edit_btn" value="Log in">
    <input type="hidden" name="next" value="{{ next }}">

</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}

workspace/templates/workspace/marks_add_ent.html
{% extends "./generic_edit.html" %}

{% block title %} Add control entity {% endblock %}
{% block title2 %} Add control entity {% endblock %}
{% block action_url %} {% url 'workspace:marks_add_ent' this_course.id %} {% endblock %}
{% block subheader %} <h5> Add control entity for course {{ this_course }}: </h5> {% endblock %}

workspace/templates/workspace/marks_detail.html
{% extends "./base.html" %}

{% block title %} Marks {% endblock %}
{% block title2 %} Marks for {{ this_entity }} {% endblock %}
{% block content %}
    <h5> Marks for {{ this_entity.name }}: </h5>
    <div> {{ this_entity.etype }}  </div>
    <div> Deadline: {{ this_entity.deadline }}  </div>
    <div> Highest mark: {{ this_entity.mark_max }}  </div>
    <div> Study materials: </div>
    <div>  "{{ this_entity.materials }}" </div>
    <a href="{% url 'workspace:marks_entities' this_entity.course.id %}"> <- Back to course </a>
    {% if marks_list|length > 0  %}
        <div class="table_container">
        <table >
            <tr>
                <th>Students</th>
                <th>Mark</th>
            </tr>
            {% for st, mark in marks_list %}
                <tr>
                    <td >{{ st }}</td>
                    <td >{{ mark }}</td>
                </tr>
            {% endfor %}
        </table>
        </div>
    {% elif marks_list %}
        <p> Empty </p>
    {% else %}
        <p> These aren't the Droids you're looking for... </p>
    {% endif %}
    {% if auth_teacher %}
        <a class="edit_btn" href="{% url 'workspace:marks_edit' this_entity.course.pk this_entity.pk %}" > Edit marks </a>
        <a class="edit_btn" href="{% url 'workspace:marks_entity_change' this_entity.course.pk this_entity.pk %}" > Edit control entity </a>
        <button class="delete_btn btn_r" onclick="delete_confirm('control entity', '{% url 'workspace:marks_entity_rm' this_entity.course.pk this_entity.pk %}')" > Remove this entity </button>
    {% endif %}

{% endblock %}

workspace/templates/workspace/marks_edit.html
{% extends "./base.html" %}

{% block title %} Edit {% endblock %}
{% block title2 %} Edit Marks for {{ this_entity }} {% endblock %}
{% block content %}
    <h5> Edit marks for {{ this_entity.name }}: </h5>

    {% if student_forms %}
        <form action="{% url 'workspace:marks_edit' this_entity.course.pk this_entity.pk %}" method="post">
            {% csrf_token %}
            <div>{{ student_forms.management_form }}</div>
            <div>{{ form.non_field_errors }}</div>
            <table class="marks_table">
                <tr>
                    <th>Students</th>
                    <th>Mark</th>
                </tr>
                {% for form in student_forms %}
                <tr>
                    <td >{{ form.student }} {{ form.student.initial }} {{ form.student.errors }} </td>
                    <td >{{ form.mark }} {{ form.mark.errors }} </td>
                </tr>
                {% endfor %}
            </table>
            <input type="submit" value="Submit">
        </form>
        <p >{{ c_message }}</p>
    {% endif %}
{% endblock %}

workspace/templates/workspace/marks_menu.html
{% extends "./base.html" %}

{% block title %} Courses {% endblock %}
{% block title2 %} Courses for {{ request.user.username }} {% endblock %}
{% block content %}
    <h5> Here you can check your courses: </h5>
    <ul>
        {% if auth_teacher %}
            {% for course in user_courses %}
                <li class=marks_li><a href="{% url 'workspace:marks_entities' course.id %}">{{ course.discipline }} {{ course.group }}</a></li>
            {% empty %}
                    <p>No curated courses</p>
            {% endfor %}
            {% if extra_courses %}
                </ul>
                <p> --Extra courses:-- </p>
                <ul>
                {% for c in extra_courses %}
                    <li class=marks_li><a href="{% url 'workspace:marks_entities' c.id %}">{{ c.discipline }} {{ c.group }}</a></li>
                {% endfor %}
            {% endif %}
            </ul>
        {% elif auth_student %}
            {% for course in user_courses %}
                <li class=marks_li> <a href="{% url 'workspace:marks_entities' course.id %}"> {{ course.discipline }} </a></li>
            {% empty %}
                <p>Currently you don't have any courses</p>
            {% endfor %}
            </ul>
        {% else %}
            <p class="mytmp"> These aren't the Droids you're looking for... </p>
        {% endif %}
{% endblock %}

workspace/templates/workspace/marks_table.html
{% extends "./base.html" %}

{% block title %} Marks table {% endblock %}
{% block title2 %} Marks for {{ this_course }} {% endblock %}
{% block content %}
    {% if marks_table %}
        <h5> Marks table of course {{ this_course }}: </h5>
        <div class="table_container">
        <table class="marks_table" style="overflow: auto;">
            <tr>
                <th class="start_col"> <p> Student </p></th>
                {% for ce in ce_list %}
                    <th class="tmark"> <p> {{ce.name}}</p> </th>
                {% endfor %}
                <th class="tmark total_col"> <p> Total </p></th>
            </tr>
            {% for st, marks, total in marks_table %}
            <tr>
                <td class="start_col" >{{ st }}</td>
                {% for m in marks %}
                    <td class="tmark">{{ m.mark }}</td>
                {% endfor %}
                <td class="tmark total_col">{{ total }}</td>
            </tr>
            {% endfor %}
        </table>
        </div>
    {% else %}
        <p> Page broke </p>
    {% endif %}
    <a href="{% url 'workspace:marks_entities' this_course.id %}"> <- Back to course </a>
{% endblock %}

workspace/templates/workspace/notifications.html
<div class="notification-container">
    <div class="notification-button" onclick="popup_show()">New notifications {{ n.created }}</div>
    <div class="notification-content" id="NotifCont">
         {% for n in notifications %}
            <div class="notification-instance" >
                <div><span class="minitext" >{{ n.created }}</span>
                <a class="minitext close" href="{% url 'workspace:rm_notif' n.id %}" onclick="rm_notification(this)">X</a></div>
                {% if n.link %}
                    <a href={{n.link}} class="notetext">{{ n.note }}</a>
                {% else %}
                    <a class="notetext">{{ n.note }}</a>
                {% endif %}
            </div>
         {% endfor %}
    </div>
</div>

workspace/templates/workspace/profile.html
{% extends "./base.html" %}

{% block title %} Profile {% endblock %}
{% block title2 %} Profile {% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
        <div class="table_container">
        <table class= "double_table">
            <tr>
                <td>Username:</td>
                <td>{{request.user.username}}</td>
            </tr>
            <tr>
                <td>E-mail:</td>
                <td>{{request.user.email}}</td>
            </tr>
            <tr>
                <td>First name:</td>
                <td>{{request.user.first_name}}</td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td>{{request.user.last_name}}</td>
            </tr>
            <tr>
                <td>Status:</td>
                <td>
                    {% if request.user.teacher %} Teacher {% endif %}
                    {% if request.user.student %} Student {% endif %}
                    {% if request.user.is_staff %} Staff {% endif %}
                </td>
            </tr>
            {% if request.user.teacher %}
                <tr>
                    <td>Qualification:</td>
                    <td>{{request.user.teacher.qualification}}</td>
                </tr>
                <tr>
                    <td>Page:</td>
                    <td><a href="{{request.user.teacher.page}}" target="_blank">{{request.user.teacher.page}}</a></td>
                </tr>

            {% elif request.user.student %}
                <tr>
                    <td>Student ID number:</td>
                    <td>{{request.user.student.card_id_number}}</td>
                </tr>
                <tr>
                    <td>Group:</td>
                    <td>{{request.user.student.group.name}}</td>
                </tr>
                <tr>
                    <td>Github:</td>
                    <td>{{request.user.student.github}}</td>
                </tr>
            {% endif %}
        </table>
        </div>
        <a href="{% url 'workspace:logout' %}">Logout</a>
        <a class="edit_btn btn_r" href="{% url 'workspace:profile_edit' %}" > Edit profile </a>
    {% else %}
        <p>Please log in</p>
    {% endif %}
{% endblock %}

workspace/templates/workspace/sidebar.html
<div class="list-group">
    <a class="list-group-item list-group-item-action" href="{% url 'workspace:index' %}"> Home </a>
    {% if not user.is_authenticated %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:login' %}"> Login </a>
</div>
    {% else %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:profile' %}"> Profile </a>
        {% if request.user.teacher or request.user.student %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:schedule' %}"> My Schedule </a>
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:marks_menu' %}"> Marks and control </a>
        {% endif %}
        {% if request.user.teacher %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:lesson_add' %}"> Add lesson </a>
        {% endif %}
        {% if user.is_staff %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:batch_add' %}"> Staff functions </a>
        {% endif %}
        <a class="list-group-item list-group-item-action" href="{% url 'workspace:logout' %}"> Logout </a>
</div>
        {% if notifications %}
            {% include "./notifications.html" %}
        {% endif %}
    {% endif %}